//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.giga.dms.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "DMSServices", targetNamespace = "http://services.dms.giga.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DMSServices {


    /**
     * 
     * @param document
     * @return
     *     returns java.util.List<com.giga.dms.services.DocumentVO>
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchDocuments", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.SearchDocuments")
    @ResponseWrapper(localName = "searchDocumentsResponse", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.SearchDocumentsResponse")
    public List<DocumentVO> searchDocuments(
        @WebParam(name = "document", targetNamespace = "")
        DocumentVO document)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param documentCollection
     * @return
     *     returns java.util.List<com.giga.dms.services.DocumentVO>
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadDocuments", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.UploadDocuments")
    @ResponseWrapper(localName = "uploadDocumentsResponse", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.UploadDocumentsResponse")
    public List<DocumentVO> uploadDocuments(
        @WebParam(name = "documentCollection", targetNamespace = "")
        List<DocumentVO> documentCollection)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param document
     * @return
     *     returns com.giga.dms.services.DocumentVO
     * @throws ServiceException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewDocument", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.ViewDocument")
    @ResponseWrapper(localName = "viewDocumentResponse", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.ViewDocumentResponse")
    public DocumentVO viewDocument(
        @WebParam(name = "document", targetNamespace = "")
        DocumentVO document)
        throws IOException_Exception, ServiceException_Exception
    ;

    /**
     * 
     * @param document
     * @return
     *     returns java.lang.String
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteDocument", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.DeleteDocument")
    @ResponseWrapper(localName = "deleteDocumentResponse", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.DeleteDocumentResponse")
    public String deleteDocument(
        @WebParam(name = "document", targetNamespace = "")
        DocumentVO document)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param documentCollection
     * @return
     *     returns java.util.List<com.giga.dms.services.DocumentVO>
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "downloadDocuments", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.DownloadDocuments")
    @ResponseWrapper(localName = "downloadDocumentsResponse", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.DownloadDocumentsResponse")
    public List<DocumentVO> downloadDocuments(
        @WebParam(name = "documentCollection", targetNamespace = "")
        List<DocumentVO> documentCollection)
        throws ServiceException_Exception
    ;

    /**
     * 
     * @param document
     * @return
     *     returns byte[]
     * @throws ServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mergeDocuments", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.MergeDocuments")
    @ResponseWrapper(localName = "mergeDocumentsResponse", targetNamespace = "http://services.dms.giga.com/", className = "com.giga.dms.services.MergeDocumentsResponse")
    public byte[] mergeDocuments(
        @WebParam(name = "document", targetNamespace = "")
        DocumentVO document)
        throws ServiceException_Exception
    ;

}
