package com.giga.dms.util;



public enum DMSGType {
	SEARCH_BOOKING,SEARCH_JOB,SEARCH_SI,SEARCH_CLAIM,SEARCH_SHIPMENT,SEARCH_INVOICE,SEARCH_QUOTATION,SEARCH_PO,SEARCH_DO,SEARCH_LOAD,SEARCH_BOOKING_CUSTOMER,LOAD_DOC_TYPE,
	DMS_CONTNET_SEARCH,SEARCH_DEBITNOTE,SEARCH_CREDITNOTE,
	DMS_DOCUMENT_LINE,DMS_DOCUMENT_TYPE,DMS_BOOKING_NO,DMS_JOB_NO,DMS_SI_NO,DMS_CLAIM_NO,DMS_QUOTATION_NO,DMS_INVOICE_NO,DMS_PO_NO,DMS_DO_NO,
	DMS_LOAD_NO,DMS_BOOKING_CUSTOMER,DMS_UPLOAD_FORM_DATE,DMS_UPLOAD_TO_DATE,

	DMS_BOOKINGNO_PODS,
	DMS_BOOKINGNO_SERVICETYPES,
	DMS_BOOKINGNO_SERVICELINES,
	DMS_BOOKINGNO_CARGOTYPES,
	DMS_BOOKINGNO_BUSINESSLINE,
	DMS_LOAD_BOOKINGCUS_AND_BUSINESSLINE,
	SEARCH_DELIVERYNOTE,SEARCH_PULLINGORDER;
}
