package com.giga.dms.util;


public enum DMSMetaDataKeys {
	SYSTEM_LINE,DOCUMENT_LINE,DOCUMENT_TYPE,BOOKING_NUMBER,JOB_NUMBER,SI_NUMBER,CLAIM_NUMBER,SHIPMENT_NUMBER,INVOICE_NUMBER,QUOTATION_NO,BUSINESS_LINE,SERVICE_TYPE,SERVICE_LINE,BOOKIN_CUSTOMER,PORT_OF_DISCHARGE,
	CARGO_TYPE,VESSEL_NAME,VOYAGE_NUMBER,UPLOAD_BY,DOCUMENT_TITLE,UPLOAD_FROM_DATE,UPLOAD_TO_DATE,DMS_ID,MIME_TYPE,DO_NO,PO_NO,LOAD_NO,PORT_OF_LOADING,DELETE_BY,CREDIT_NOTE_NO,DEBIT_NOTE_NO,INCIDENT_NO,
	QUOTATION_DATE,CREDITNOTE_DATE,DEBITNOTE_DATE,INVOICE_DATE,PODATE,COMPANY_CODE,
	INCIDENT_DETAILS,CONSIGNEE,CHASSIS_NO,INSURANCE_AGENT,RESPONSIBLE_PARTY,IS_CANCELLED, 
	CLAIM_TYPE,CLAIM_DATE,INCIDENT_DATE,REMARKS,DELIVERYNOTE_NO,FORWARDINGAGENT_NAME,PULLINGORDER_NO;
}
