package com.giga.dms.dao.domain;

// Generated 26 May, 2015 8:49:20 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DmsDocumentAuditHistory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "DMS_DOCUMENT_AUDIT_HISTORY", schema = "DMSTxn", catalog = "OFSDB")
public class DmsDocumentAuditHistory implements java.io.Serializable {

	private long daId; 
	private String documentNumber;
	private String sourceSystem;
	private String actionBy;
	private Date actionDate;
	private String remarks;

	public DmsDocumentAuditHistory() {
	}

	public DmsDocumentAuditHistory(long daId, String documentNumber,
			String sourceSystem, String actionBy, Date actionDate) {
		this.daId = daId;
		this.documentNumber = documentNumber;
		this.sourceSystem = sourceSystem;
		this.actionBy = actionBy;
		this.actionDate = actionDate;
	}

	public DmsDocumentAuditHistory(long daId, String documentNumber,
			String sourceSystem, String actionBy, Date actionDate,
			String remarks) {
		this.daId = daId;
		this.documentNumber = documentNumber;
		this.sourceSystem = sourceSystem;
		this.actionBy = actionBy;
		this.actionDate = actionDate;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "DA_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getDaId() {
		return this.daId;
	}

	public void setDaId(long daId) {
		this.daId = daId;
	}

	@Column(name = "DOCUMENT_NUMBER", nullable = false, length = 40)
	public String getDocumentNumber() {
		return this.documentNumber;
	}

	public void setDocumentNumber(String documentNumber) {
		this.documentNumber = documentNumber;
	}

	@Column(name = "SOURCE_SYSTEM", nullable = false, length = 10)
	public String getSourceSystem() {
		return this.sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

	@Column(name = "ACTION_BY", nullable = false, length = 40)
	public String getActionBy() {
		return this.actionBy;
	}

	public void setActionBy(String actionBy) {
		this.actionBy = actionBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTION_DATE", nullable = false, length = 23)
	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	@Column(name = "REMARKS")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
