//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "associateID",
    "amount",
    "outboundTillID",
    "outboundTillEmployeePartyID",
    "cashRemainedInTill"
})
@XmlRootElement(name = "AssociateAdvance", namespace = "http://www.datavantagecorp.com/xstore/")
public class AssociateAdvance {

    @XmlElement(name = "AssociateID", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String associateID;
    @XmlElement(name = "Amount", namespace = "http://www.datavantagecorp.com/xstore/")
    protected DtvAmountType amount;
    @XmlElement(name = "OutboundTillID", namespace = "http://www.datavantagecorp.com/xstore/")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String outboundTillID;
    @XmlElement(name = "OutboundTillEmployeePartyID", namespace = "http://www.datavantagecorp.com/xstore/")
    protected BigInteger outboundTillEmployeePartyID;
    @XmlElement(name = "CashRemainedInTill", namespace = "http://www.datavantagecorp.com/xstore/")
    protected List<CashRemainedInTillType> cashRemainedInTill;

    /**
     * Gets the value of the associateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociateID() {
        return associateID;
    }

    /**
     * Sets the value of the associateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociateID(String value) {
        this.associateID = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link DtvAmountType }
     *     
     */
    public DtvAmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link DtvAmountType }
     *     
     */
    public void setAmount(DtvAmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the outboundTillID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutboundTillID() {
        return outboundTillID;
    }

    /**
     * Sets the value of the outboundTillID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutboundTillID(String value) {
        this.outboundTillID = value;
    }

    /**
     * Gets the value of the outboundTillEmployeePartyID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutboundTillEmployeePartyID() {
        return outboundTillEmployeePartyID;
    }

    /**
     * Sets the value of the outboundTillEmployeePartyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutboundTillEmployeePartyID(BigInteger value) {
        this.outboundTillEmployeePartyID = value;
    }

    /**
     * Gets the value of the cashRemainedInTill property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashRemainedInTill property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashRemainedInTill().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashRemainedInTillType }
     * 
     * 
     */
    public List<CashRemainedInTillType> getCashRemainedInTill() {
        if (cashRemainedInTill == null) {
            cashRemainedInTill = new ArrayList<CashRemainedInTillType>();
        }
        return this.cashRemainedInTill;
    }

}
