//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tillID",
    "workstationID",
    "cashDrawer"
})
@XmlRootElement(name = "AttachTill", namespace = "http://www.datavantagecorp.com/xstore/")
public class AttachTill {

    @XmlElement(name = "TillID", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tillID;
    @XmlElement(name = "WorkstationID", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    protected String workstationID;
    @XmlElement(name = "CashDrawer", namespace = "http://www.datavantagecorp.com/xstore/")
    protected BigInteger cashDrawer;

    /**
     * Gets the value of the tillID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTillID() {
        return tillID;
    }

    /**
     * Sets the value of the tillID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTillID(String value) {
        this.tillID = value;
    }

    /**
     * Gets the value of the workstationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkstationID() {
        return workstationID;
    }

    /**
     * Sets the value of the workstationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkstationID(String value) {
        this.workstationID = value;
    }

    /**
     * Gets the value of the cashDrawer property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCashDrawer() {
        return cashDrawer;
    }

    /**
     * Sets the value of the cashDrawer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCashDrawer(BigInteger value) {
        this.cashDrawer = value;
    }

}
