//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EscrowTransactionType", propOrder = {
    "transactionType",
    "customer",
    "lineItem",
    "escrowTransferToAccount",
    "escrowTransferFromAccount"
})
public class EscrowTransactionType {

    @XmlElement(name = "TransactionType", required = true)
    protected String transactionType;
    @XmlElement(name = "Customer", required = true)
    protected PoslogCustomerType customer;
    @XmlElement(name = "LineItem")
    protected List<LineItemType> lineItem;
    @XmlElement(name = "EscrowTransferToAccount", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    protected EscrowTransferToAccount escrowTransferToAccount;
    @XmlElement(name = "EscrowTransferFromAccount", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    protected EscrowTransferFromAccount escrowTransferFromAccount;

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionType(String value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link PoslogCustomerType }
     *     
     */
    public PoslogCustomerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoslogCustomerType }
     *     
     */
    public void setCustomer(PoslogCustomerType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the lineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineItemType }
     * 
     * 
     */
    public List<LineItemType> getLineItem() {
        if (lineItem == null) {
            lineItem = new ArrayList<LineItemType>();
        }
        return this.lineItem;
    }

    /**
     * Gets the value of the escrowTransferToAccount property.
     * 
     * @return
     *     possible object is
     *     {@link EscrowTransferToAccount }
     *     
     */
    public EscrowTransferToAccount getEscrowTransferToAccount() {
        return escrowTransferToAccount;
    }

    /**
     * Sets the value of the escrowTransferToAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link EscrowTransferToAccount }
     *     
     */
    public void setEscrowTransferToAccount(EscrowTransferToAccount value) {
        this.escrowTransferToAccount = value;
    }

    /**
     * Gets the value of the escrowTransferFromAccount property.
     * 
     * @return
     *     possible object is
     *     {@link EscrowTransferFromAccount }
     *     
     */
    public EscrowTransferFromAccount getEscrowTransferFromAccount() {
        return escrowTransferFromAccount;
    }

    /**
     * Sets the value of the escrowTransferFromAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link EscrowTransferFromAccount }
     *     
     */
    public void setEscrowTransferFromAccount(EscrowTransferFromAccount value) {
        this.escrowTransferFromAccount = value;
    }

}
