//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExchangeType", propOrder = {
    "newSerialNumber",
    "originalSerialNumber",
    "reason",
    "reasonComment"
})
public class ExchangeType
    extends SaleType
{

    @XmlElement(name = "NewSerialNumber", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    protected String newSerialNumber;
    @XmlElement(name = "OriginalSerialNumber", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    protected String originalSerialNumber;
    @XmlElement(name = "Reason", required = true)
    protected String reason;
    @XmlElement(name = "ReasonComment", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    protected String reasonComment;

    /**
     * Gets the value of the newSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewSerialNumber() {
        return newSerialNumber;
    }

    /**
     * Sets the value of the newSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewSerialNumber(String value) {
        this.newSerialNumber = value;
    }

    /**
     * Gets the value of the originalSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalSerialNumber() {
        return originalSerialNumber;
    }

    /**
     * Sets the value of the originalSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalSerialNumber(String value) {
        this.originalSerialNumber = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReason(String value) {
        this.reason = value;
    }

    /**
     * Gets the value of the reasonComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonComment() {
        return reasonComment;
    }

    /**
     * Sets the value of the reasonComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonComment(String value) {
        this.reasonComment = value;
    }

}
