//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InventoryCountType", propOrder = {
    "countID",
    "countType",
    "countStatus"
})
public class InventoryCountType {

    @XmlElement(name = "CountID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String countID;
    @XmlElement(name = "CountType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String countType;
    @XmlElement(name = "CountStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String countStatus;

    /**
     * Gets the value of the countID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountID() {
        return countID;
    }

    /**
     * Sets the value of the countID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountID(String value) {
        this.countID = value;
    }

    /**
     * Gets the value of the countType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountType() {
        return countType;
    }

    /**
     * Sets the value of the countType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountType(String value) {
        this.countType = value;
    }

    /**
     * Gets the value of the countStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountStatus() {
        return countStatus;
    }

    /**
     * Sets the value of the countStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountStatus(String value) {
        this.countStatus = value;
    }

}
