//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineItemPropertyType", namespace = "http://www.datavantagecorp.com/xstore/", propOrder = {
    "lineItemPropertyCode",
    "lineItemPropertyType",
    "lineItemPropertyValue",
    "lineItemPropertyDate",
    "lineItemPropertyDecimal"
})
public class LineItemPropertyType {

    @XmlElement(name = "LineItemPropertyCode", required = true)
    protected String lineItemPropertyCode;
    @XmlElement(name = "LineItemPropertyType")
    protected String lineItemPropertyType;
    @XmlElement(name = "LineItemPropertyValue")
    protected String lineItemPropertyValue;
    @XmlElement(name = "LineItemPropertyDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lineItemPropertyDate;
    @XmlElement(name = "LineItemPropertyDecimal")
    protected BigDecimal lineItemPropertyDecimal;

    /**
     * Gets the value of the lineItemPropertyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineItemPropertyCode() {
        return lineItemPropertyCode;
    }

    /**
     * Sets the value of the lineItemPropertyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineItemPropertyCode(String value) {
        this.lineItemPropertyCode = value;
    }

    /**
     * Gets the value of the lineItemPropertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineItemPropertyType() {
        return lineItemPropertyType;
    }

    /**
     * Sets the value of the lineItemPropertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineItemPropertyType(String value) {
        this.lineItemPropertyType = value;
    }

    /**
     * Gets the value of the lineItemPropertyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineItemPropertyValue() {
        return lineItemPropertyValue;
    }

    /**
     * Sets the value of the lineItemPropertyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineItemPropertyValue(String value) {
        this.lineItemPropertyValue = value;
    }

    /**
     * Gets the value of the lineItemPropertyDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLineItemPropertyDate() {
        return lineItemPropertyDate;
    }

    /**
     * Sets the value of the lineItemPropertyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLineItemPropertyDate(XMLGregorianCalendar value) {
        this.lineItemPropertyDate = value;
    }

    /**
     * Gets the value of the lineItemPropertyDecimal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLineItemPropertyDecimal() {
        return lineItemPropertyDecimal;
    }

    /**
     * Sets the value of the lineItemPropertyDecimal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLineItemPropertyDecimal(BigDecimal value) {
        this.lineItemPropertyDecimal = value;
    }

}
