//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

@XmlRegistry
public class ObjectFactory {

    private final static QName _CashTransfer_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "CashTransfer");
    private final static QName _PosTransactionProperties_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PosTransactionProperties");
    private final static QName _DiscountReasonCodeComment_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "DiscountReasonCodeComment");
    private final static QName _ResponseSequenceNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ResponseSequenceNumber");
    private final static QName _TillClosingCount_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TillClosingCount");
    private final static QName _EmployeeSaleId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "EmployeeSaleId");
    private final static QName _ApprovalFlag_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ApprovalFlag");
    private final static QName _WeightEntryMethodCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "WeightEntryMethodCode");
    private final static QName _NewSerialNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "NewSerialNumber");
    private final static QName _PostVoidReasonCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PostVoidReasonCode");
    private final static QName _AuthorizationToken_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "AuthorizationToken");
    private final static QName _TillReconcileCount_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TillReconcileCount");
    private final static QName _ScannedItemID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ScannedItemID");
    private final static QName _Address1_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Address1");
    private final static QName _Address2_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Address2");
    private final static QName _MaskedCardNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "MaskedCardNumber");
    private final static QName _Address3_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Address3");
    private final static QName _DocumentType_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "DocumentType");
    private final static QName _Contact_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Contact");
    private final static QName _SafeBag_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "SafeBag");
    private final static QName _ResponseCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ResponseCode");
    private final static QName _CardLevelIndicator_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "CardLevelIndicator");
    private final static QName _UserName_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "UserName");
    private final static QName _PostVoidComment_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PostVoidComment");
    private final static QName _AuthorizationCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "AuthorizationCode");
    private final static QName _TillID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TillID");
    private final static QName _LocalCurrencyPickup_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "LocalCurrencyPickup");
    private final static QName _LineItemProperty_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "LineItemProperty");
    private final static QName _ActivityCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ActivityCode");
    private final static QName _StoreBankAudit_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "StoreBankAudit");
    private final static QName _OriginalSerialNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "OriginalSerialNumber");
    private final static QName _AssignTillTenderTransfer_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "AssignTillTenderTransfer");
    private final static QName _TareValue_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TareValue");
    private final static QName _ContactFlag_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ContactFlag");
    private final static QName _TareUnitOfMeasureCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TareUnitOfMeasureCode");
    private final static QName _Address4_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Address4");
    private final static QName _Duty_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Duty");
    private final static QName _VoidReason_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "VoidReason");
    private final static QName _PercentOff_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PercentOff");
    private final static QName _ActionCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ActionCode");
    private final static QName _PostalCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PostalCode");
    private final static QName _County_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "County");
    private final static QName _FiscalSessionNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "FiscalSessionNumber");
    private final static QName _UnitOfMeasureCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "UnitOfMeasureCode");
    private final static QName _Discount_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Discount");
    private final static QName _FiscalNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "FiscalNumber");
    private final static QName _DeviceId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "DeviceId");
    private final static QName _PercentageOfItem_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PercentageOfItem");
    private final static QName _SeriesId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "SeriesId");
    private final static QName _ResponseText_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ResponseText");
    private final static QName _MidDayTillDeposit_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "MidDayTillDeposit");
    private final static QName _FiscalItemDescription_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "FiscalItemDescription");
    private final static QName _Country_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Country");
    private final static QName _DiscountReasonCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "DiscountReasonCode");
    private final static QName _ExpirationDateEncrypted_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ExpirationDateEncrypted");
    private final static QName _CashDrawerID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "CashDrawerID");
    private final static QName _LinkTypeCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "LinkTypeCode");
    private final static QName _SerialNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "SerialNumber");
    private final static QName _DiplomaticTitle_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "DiplomaticTitle");
    private final static QName _RawTaxPercentage_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "RawTaxPercentage");
    private final static QName _OrganizationID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "OrganizationID");
    private final static QName _City_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "City");
    private final static QName _Neighborhood_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Neighborhood");
    private final static QName _ReturnType_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ReturnType");
    private final static QName _HashedCardNumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "HashedCardNumber");
    private final static QName _MallCertificateID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "MallCertificateID");
    private final static QName _Territory_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Territory");
    private final static QName _ErrorText_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ErrorText");
    private final static QName _TaxLocationId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TaxLocationId");
    private final static QName _QuantityShipped_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "QuantityShipped");
    private final static QName _ReasonComment_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "ReasonComment");
    private final static QName _PayDeduct_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PayDeduct");
    private final static QName _TaxGroupId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TaxGroupId");
    private final static QName _AdjudicationCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "AdjudicationCode");
    private final static QName _Freight_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Freight");
    private final static QName _FiscalTenderID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "FiscalTenderID");
    private final static QName _MeasurementRequired_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "MeasurementRequired");
    private final static QName _OrderType_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "OrderType");
    private final static QName _POSLog_QNAME = new QName("http://www.nrf-arts.org/IXRetail/namespace/", "POSLog");
    private final static QName _TransCancelReasonCode_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TransCancelReasonCode");
    private final static QName _InboundTillID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "InboundTillID");
    private final static QName _Tax_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Tax");
    private final static QName _CustomerID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "CustomerID");
    private final static QName _LocalCurrencyDeposit_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "LocalCurrencyDeposit");
    private final static QName _DocumentId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "DocumentId");
    private final static QName _DiscountId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "DiscountId");
    private final static QName _Ps2000_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "Ps2000");
    private final static QName _InventoryBucketId_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "InventoryBucketId");
    private final static QName _BankDeposit_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "BankDeposit");
    private final static QName _PONumber_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "PONumber");
    private final static QName _TillAudit_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TillAudit");
    private final static QName _FiscalItemID_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "FiscalItemID");
    private final static QName _BeginTillCount_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "BeginTillCount");
    private final static QName _TareType_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "TareType");
    private final static QName _SystemCycleType_QNAME = new QName("http://www.datavantagecorp.com/xstore/", "SystemCycleType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.backbounty.test
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link POSLogType }
     * 
     */
    public POSLogType createPOSLogType() {
        return new POSLogType();
    }

    /**
     * Create an instance of {@link CustomerOrderForPickupType }
     * 
     */
    public CustomerOrderForPickupType createCustomerOrderForPickupType() {
        return new CustomerOrderForPickupType();
    }

    /**
     * Create an instance of {@link SaleType }
     * 
     */
    public SaleType createSaleType() {
        return new SaleType();
    }

    /**
     * Create an instance of {@link LineItemType }
     * 
     */
    public LineItemType createLineItemType() {
        return new LineItemType();
    }

    /**
     * Create an instance of {@link TravelersCheckType }
     * 
     */
    public TravelersCheckType createTravelersCheckType() {
        return new TravelersCheckType();
    }

    /**
     * Create an instance of {@link AssociateType }
     * 
     */
    public AssociateType createAssociateType() {
        return new AssociateType();
    }

    /**
     * Create an instance of {@link CouponType }
     * 
     */
    public CouponType createCouponType() {
        return new CouponType();
    }

    /**
     * Create an instance of {@link MerchandiseHierarchyType }
     * 
     */
    public MerchandiseHierarchyType createMerchandiseHierarchyType() {
        return new MerchandiseHierarchyType();
    }

    /**
     * Create an instance of {@link EscrowTransactionType }
     * 
     */
    public EscrowTransactionType createEscrowTransactionType() {
        return new EscrowTransactionType();
    }

    /**
     * Create an instance of {@link LayawayType }
     * 
     */
    public LayawayType createLayawayType() {
        return new LayawayType();
    }

    /**
     * Create an instance of {@link CustomerOrderForDeliveryType }
     * 
     */
    public CustomerOrderForDeliveryType createCustomerOrderForDeliveryType() {
        return new CustomerOrderForDeliveryType();
    }

    /**
     * Create an instance of {@link PoslogAddressType }
     * 
     */
    public PoslogAddressType createPoslogAddressType() {
        return new PoslogAddressType();
    }

    /**
     * Create an instance of {@link AddressLineType }
     * 
     */
    public AddressLineType createAddressLineType() {
        return new AddressLineType();
    }

    /**
     * Create an instance of {@link ShipmentType }
     * 
     */
    public ShipmentType createShipmentType() {
        return new ShipmentType();
    }

    /**
     * Create an instance of {@link CreditDebitType }
     * 
     */
    public CreditDebitType createCreditDebitType() {
        return new CreditDebitType();
    }

    /**
     * Create an instance of {@link ItemTransferLineType }
     * 
     */
    public ItemTransferLineType createItemTransferLineType() {
        return new ItemTransferLineType();
    }

    /**
     * Create an instance of {@link TillControlTransactionType }
     * 
     */
    public TillControlTransactionType createTillControlTransactionType() {
        return new TillControlTransactionType();
    }

    /**
     * Create an instance of {@link StoreStructure }
     * 
     */
    public StoreStructure createStoreStructure() {
        return new StoreStructure();
    }

    /**
     * Create an instance of {@link ItemAccountModifierType }
     * 
     */
    public ItemAccountModifierType createItemAccountModifierType() {
        return new ItemAccountModifierType();
    }

    /**
     * Create an instance of {@link ExchangeType }
     * 
     */
    public ExchangeType createExchangeType() {
        return new ExchangeType();
    }

    /**
     * Create an instance of {@link DeliveryType }
     * 
     */
    public DeliveryType createDeliveryType() {
        return new DeliveryType();
    }

    /**
     * Create an instance of {@link SendCheckType }
     * 
     */
    public SendCheckType createSendCheckType() {
        return new SendCheckType();
    }

    /**
     * Create an instance of {@link InventoryCountType }
     * 
     */
    public InventoryCountType createInventoryCountType() {
        return new InventoryCountType();
    }

    /**
     * Create an instance of {@link CartonType }
     * 
     */
    public CartonType createCartonType() {
        return new CartonType();
    }

    /**
     * Create an instance of {@link ControlTransactionType }
     * 
     */
    public ControlTransactionType createControlTransactionType() {
        return new ControlTransactionType();
    }

    /**
     * Create an instance of {@link ItemCountType }
     * 
     */
    public ItemCountType createItemCountType() {
        return new ItemCountType();
    }

    /**
     * Create an instance of {@link ReturnType }
     * 
     */
    public ReturnType createReturnType() {
        return new ReturnType();
    }

    /**
     * Create an instance of {@link SaleForPickupType }
     * 
     */
    public SaleForPickupType createSaleForPickupType() {
        return new SaleForPickupType();
    }

    /**
     * Create an instance of {@link DisposalType }
     * 
     */
    public DisposalType createDisposalType() {
        return new DisposalType();
    }

    /**
     * Create an instance of {@link TaxType }
     * 
     */
    public TaxType createTaxType() {
        return new TaxType();
    }

    /**
     * Create an instance of {@link TerritoryType }
     * 
     */
    public TerritoryType createTerritoryType() {
        return new TerritoryType();
    }

    /**
     * Create an instance of {@link TenderExchangeType }
     * 
     */
    public TenderExchangeType createTenderExchangeType() {
        return new TenderExchangeType();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link DiscountType }
     * 
     */
    public DiscountType createDiscountType() {
        return new DiscountType();
    }

    /**
     * Create an instance of {@link TenderControlTransactionType }
     * 
     */
    public TenderControlTransactionType createTenderControlTransactionType() {
        return new TenderControlTransactionType();
    }

    /**
     * Create an instance of {@link KitType }
     * 
     */
    public KitType createKitType() {
        return new KitType();
    }

    /**
     * Create an instance of {@link PickupType }
     * 
     */
    public PickupType createPickupType() {
        return new PickupType();
    }

    /**
     * Create an instance of {@link AuthorizationType }
     * 
     */
    public AuthorizationType createAuthorizationType() {
        return new AuthorizationType();
    }

    /**
     * Create an instance of {@link CustomerAccountType }
     * 
     */
    public CustomerAccountType createCustomerAccountType() {
        return new CustomerAccountType();
    }

    /**
     * Create an instance of {@link VoucherType }
     * 
     */
    public VoucherType createVoucherType() {
        return new VoucherType();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link PoslogCustomerType }
     * 
     */
    public PoslogCustomerType createPoslogCustomerType() {
        return new PoslogCustomerType();
    }

    /**
     * Create an instance of {@link RetailPriceModifierType }
     * 
     */
    public RetailPriceModifierType createRetailPriceModifierType() {
        return new RetailPriceModifierType();
    }

    /**
     * Create an instance of {@link TaxExemptionType }
     * 
     */
    public TaxExemptionType createTaxExemptionType() {
        return new TaxExemptionType();
    }

    /**
     * Create an instance of {@link ReplenishmentOrderType }
     * 
     */
    public ReplenishmentOrderType createReplenishmentOrderType() {
        return new ReplenishmentOrderType();
    }

    /**
     * Create an instance of {@link PoslogAlternateKeyType }
     * 
     */
    public PoslogAlternateKeyType createPoslogAlternateKeyType() {
        return new PoslogAlternateKeyType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link PersonalIDType }
     * 
     */
    public PersonalIDType createPersonalIDType() {
        return new PersonalIDType();
    }

    /**
     * Create an instance of {@link PreviousLayawayType }
     * 
     */
    public PreviousLayawayType createPreviousLayawayType() {
        return new PreviousLayawayType();
    }

    /**
     * Create an instance of {@link SaleLineItemType }
     * 
     */
    public SaleLineItemType createSaleLineItemType() {
        return new SaleLineItemType();
    }

    /**
     * Create an instance of {@link ReceiptReprintType }
     * 
     */
    public ReceiptReprintType createReceiptReprintType() {
        return new ReceiptReprintType();
    }

    /**
     * Create an instance of {@link OrderLineItemType }
     * 
     */
    public OrderLineItemType createOrderLineItemType() {
        return new OrderLineItemType();
    }

    /**
     * Create an instance of {@link TenderType }
     * 
     */
    public TenderType createTenderType() {
        return new TenderType();
    }

    /**
     * Create an instance of {@link CustomerVerificationType }
     * 
     */
    public CustomerVerificationType createCustomerVerificationType() {
        return new CustomerVerificationType();
    }

    /**
     * Create an instance of {@link TenderAccountInfo }
     * 
     */
    public TenderAccountInfo createTenderAccountInfo() {
        return new TenderAccountInfo();
    }

    /**
     * Create an instance of {@link TaxOverrideType }
     * 
     */
    public TaxOverrideType createTaxOverrideType() {
        return new TaxOverrideType();
    }

    /**
     * Create an instance of {@link PaymentOnAccountType }
     * 
     */
    public PaymentOnAccountType createPaymentOnAccountType() {
        return new PaymentOnAccountType();
    }

    /**
     * Create an instance of {@link GiftCardType }
     * 
     */
    public GiftCardType createGiftCardType() {
        return new GiftCardType();
    }

    /**
     * Create an instance of {@link PreviousCustomerOrderType }
     * 
     */
    public PreviousCustomerOrderType createPreviousCustomerOrderType() {
        return new PreviousCustomerOrderType();
    }

    /**
     * Create an instance of {@link TransactionLinkType }
     * 
     */
    public TransactionLinkType createTransactionLinkType() {
        return new TransactionLinkType();
    }

    /**
     * Create an instance of {@link TillControlDetailType }
     * 
     */
    public TillControlDetailType createTillControlDetailType() {
        return new TillControlDetailType();
    }

    /**
     * Create an instance of {@link POSLogControlTransactionType }
     * 
     */
    public POSLogControlTransactionType createPOSLogControlTransactionType() {
        return new POSLogControlTransactionType();
    }

    /**
     * Create an instance of {@link InventoryTransactionType }
     * 
     */
    public InventoryTransactionType createInventoryTransactionType() {
        return new InventoryTransactionType();
    }

    /**
     * Create an instance of {@link NoteType }
     * 
     */
    public NoteType createNoteType() {
        return new NoteType();
    }

    /**
     * Create an instance of {@link InventoryMovementType }
     * 
     */
    public InventoryMovementType createInventoryMovementType() {
        return new InventoryMovementType();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

    /**
     * Create an instance of {@link PaidInOutType }
     * 
     */
    public PaidInOutType createPaidInOutType() {
        return new PaidInOutType();
    }

    /**
     * Create an instance of {@link RetailTransactionType }
     * 
     */
    public RetailTransactionType createRetailTransactionType() {
        return new RetailTransactionType();
    }

    /**
     * Create an instance of {@link CheckType }
     * 
     */
    public CheckType createCheckType() {
        return new CheckType();
    }

    /**
     * Create an instance of {@link TotalType }
     * 
     */
    public TotalType createTotalType() {
        return new TotalType();
    }

    /**
     * Create an instance of {@link ForeignCurrencyType }
     * 
     */
    public ForeignCurrencyType createForeignCurrencyType() {
        return new ForeignCurrencyType();
    }

    /**
     * Create an instance of {@link LoyaltyAccountType }
     * 
     */
    public LoyaltyAccountType createLoyaltyAccountType() {
        return new LoyaltyAccountType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link SaleForDeliveryType }
     * 
     */
    public SaleForDeliveryType createSaleForDeliveryType() {
        return new SaleForDeliveryType();
    }

    /**
     * Create an instance of {@link TillCountType }
     * 
     */
    public TillCountType createTillCountType() {
        return new TillCountType();
    }

    /**
     * Create an instance of {@link AccountCredit }
     * 
     */
    public AccountCredit createAccountCredit() {
        return new AccountCredit();
    }

    /**
     * Create an instance of {@link TimeClockTransaction }
     * 
     */
    public TimeClockTransaction createTimeClockTransaction() {
        return new TimeClockTransaction();
    }

    /**
     * Create an instance of {@link AttachTill }
     * 
     */
    public AttachTill createAttachTill() {
        return new AttachTill();
    }

    /**
     * Create an instance of {@link PayDeductType }
     * 
     */
    public PayDeductType createPayDeductType() {
        return new PayDeductType();
    }

    /**
     * Create an instance of {@link DocumentLink }
     * 
     */
    public DocumentLink createDocumentLink() {
        return new DocumentLink();
    }

    /**
     * Create an instance of {@link RemoveTill }
     * 
     */
    public RemoveTill createRemoveTill() {
        return new RemoveTill();
    }

    /**
     * Create an instance of {@link LineItemAssociation }
     * 
     */
    public LineItemAssociation createLineItemAssociation() {
        return new LineItemAssociation();
    }

    /**
     * Create an instance of {@link AssociateAdvance }
     * 
     */
    public AssociateAdvance createAssociateAdvance() {
        return new AssociateAdvance();
    }

    /**
     * Create an instance of {@link DtvAmountType }
     * 
     */
    public DtvAmountType createDtvAmountType() {
        return new DtvAmountType();
    }

    /**
     * Create an instance of {@link CashRemainedInTillType }
     * 
     */
    public CashRemainedInTillType createCashRemainedInTillType() {
        return new CashRemainedInTillType();
    }

    /**
     * Create an instance of {@link LineItemPropertyType }
     * 
     */
    public LineItemPropertyType createLineItemPropertyType() {
        return new LineItemPropertyType();
    }

    /**
     * Create an instance of {@link EscrowTransferToAccount }
     * 
     */
    public EscrowTransferToAccount createEscrowTransferToAccount() {
        return new EscrowTransferToAccount();
    }

    /**
     * Create an instance of {@link AssignTill }
     * 
     */
    public AssignTill createAssignTill() {
        return new AssignTill();
    }

    /**
     * Create an instance of {@link TransactionDeal }
     * 
     */
    public TransactionDeal createTransactionDeal() {
        return new TransactionDeal();
    }

    /**
     * Create an instance of {@link Disposition }
     * 
     */
    public Disposition createDisposition() {
        return new Disposition();
    }

    /**
     * Create an instance of {@link TrainingModeTransaction }
     * 
     */
    public TrainingModeTransaction createTrainingModeTransaction() {
        return new TrainingModeTransaction();
    }

    /**
     * Create an instance of {@link PercentageOfItemType }
     * 
     */
    public PercentageOfItemType createPercentageOfItemType() {
        return new PercentageOfItemType();
    }

    /**
     * Create an instance of {@link FlightInformation }
     * 
     */
    public FlightInformation createFlightInformation() {
        return new FlightInformation();
    }

    /**
     * Create an instance of {@link Coupon }
     * 
     */
    public Coupon createCoupon() {
        return new Coupon();
    }

    /**
     * Create an instance of {@link EscrowTransferFromAccount }
     * 
     */
    public EscrowTransferFromAccount createEscrowTransferFromAccount() {
        return new EscrowTransferFromAccount();
    }

    /**
     * Create an instance of {@link ForeignCurrencyExchangeRate }
     * 
     */
    public ForeignCurrencyExchangeRate createForeignCurrencyExchangeRate() {
        return new ForeignCurrencyExchangeRate();
    }

    /**
     * Create an instance of {@link SafeBagType }
     * 
     */
    public SafeBagType createSafeBagType() {
        return new SafeBagType();
    }

    /**
     * Create an instance of {@link PosTransactionPropertiesType }
     * 
     */
    public PosTransactionPropertiesType createPosTransactionPropertiesType() {
        return new PosTransactionPropertiesType();
    }

    /**
     * Create an instance of {@link TenderTypeSerializedCountType }
     * 
     */
    public TenderTypeSerializedCountType createTenderTypeSerializedCountType() {
        return new TenderTypeSerializedCountType();
    }

    /**
     * Create an instance of {@link TenderTotalType }
     * 
     */
    public TenderTotalType createTenderTotalType() {
        return new TenderTotalType();
    }

    /**
     * Create an instance of {@link TenderDenominationCountType }
     * 
     */
    public TenderDenominationCountType createTenderDenominationCountType() {
        return new TenderDenominationCountType();
    }

    /**
     * Create an instance of {@link PayrollDeductEmployeeType }
     * 
     */
    public PayrollDeductEmployeeType createPayrollDeductEmployeeType() {
        return new PayrollDeductEmployeeType();
    }

    /**
     * Create an instance of {@link TenderCountType }
     * 
     */
    public TenderCountType createTenderCountType() {
        return new TenderCountType();
    }

    /**
     * Create an instance of {@link TenderTypeSerializedTotalType }
     * 
     */
    public TenderTypeSerializedTotalType createTenderTypeSerializedTotalType() {
        return new TenderTypeSerializedTotalType();
    }

    /**
     * Create an instance of {@link SafeBagTransactionType }
     * 
     */
    public SafeBagTransactionType createSafeBagTransactionType() {
        return new SafeBagTransactionType();
    }

    /**
     * Create an instance of {@link TenderTypeCountType }
     * 
     */
    public TenderTypeCountType createTenderTypeCountType() {
        return new TenderTypeCountType();
    }

    /**
     * Create an instance of {@link TenderDenominationTotalType }
     * 
     */
    public TenderDenominationTotalType createTenderDenominationTotalType() {
        return new TenderDenominationTotalType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "CashTransfer")
    public JAXBElement<TillCountType> createCashTransfer(TillCountType value) {
        return new JAXBElement<TillCountType>(_CashTransfer_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PosTransactionPropertiesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PosTransactionProperties")
    public JAXBElement<PosTransactionPropertiesType> createPosTransactionProperties(PosTransactionPropertiesType value) {
        return new JAXBElement<PosTransactionPropertiesType>(_PosTransactionProperties_QNAME, PosTransactionPropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "DiscountReasonCodeComment")
    public JAXBElement<String> createDiscountReasonCodeComment(String value) {
        return new JAXBElement<String>(_DiscountReasonCodeComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ResponseSequenceNumber")
    public JAXBElement<BigInteger> createResponseSequenceNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_ResponseSequenceNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TillClosingCount")
    public JAXBElement<TillCountType> createTillClosingCount(TillCountType value) {
        return new JAXBElement<TillCountType>(_TillClosingCount_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "EmployeeSaleId")
    public JAXBElement<BigInteger> createEmployeeSaleId(BigInteger value) {
        return new JAXBElement<BigInteger>(_EmployeeSaleId_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ApprovalFlag")
    public JAXBElement<Boolean> createApprovalFlag(Boolean value) {
        return new JAXBElement<Boolean>(_ApprovalFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "WeightEntryMethodCode")
    public JAXBElement<String> createWeightEntryMethodCode(String value) {
        return new JAXBElement<String>(_WeightEntryMethodCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "NewSerialNumber")
    public JAXBElement<String> createNewSerialNumber(String value) {
        return new JAXBElement<String>(_NewSerialNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PostVoidReasonCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPostVoidReasonCode(String value) {
        return new JAXBElement<String>(_PostVoidReasonCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "AuthorizationToken")
    public JAXBElement<String> createAuthorizationToken(String value) {
        return new JAXBElement<String>(_AuthorizationToken_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TillReconcileCount")
    public JAXBElement<TillCountType> createTillReconcileCount(TillCountType value) {
        return new JAXBElement<TillCountType>(_TillReconcileCount_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ScannedItemID")
    public JAXBElement<String> createScannedItemID(String value) {
        return new JAXBElement<String>(_ScannedItemID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Address1")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddress1(String value) {
        return new JAXBElement<String>(_Address1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Address2")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "MaskedCardNumber")
    public JAXBElement<String> createMaskedCardNumber(String value) {
        return new JAXBElement<String>(_MaskedCardNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Address3")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddress3(String value) {
        return new JAXBElement<String>(_Address3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "DocumentType")
    public JAXBElement<String> createDocumentType(String value) {
        return new JAXBElement<String>(_DocumentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Contact")
    public JAXBElement<Boolean> createContact(Boolean value) {
        return new JAXBElement<Boolean>(_Contact_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SafeBagType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "SafeBag")
    public JAXBElement<SafeBagType> createSafeBag(SafeBagType value) {
        return new JAXBElement<SafeBagType>(_SafeBag_QNAME, SafeBagType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ResponseCode")
    public JAXBElement<String> createResponseCode(String value) {
        return new JAXBElement<String>(_ResponseCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "CardLevelIndicator")
    public JAXBElement<String> createCardLevelIndicator(String value) {
        return new JAXBElement<String>(_CardLevelIndicator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "UserName")
    public JAXBElement<String> createUserName(String value) {
        return new JAXBElement<String>(_UserName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PostVoidComment")
    public JAXBElement<String> createPostVoidComment(String value) {
        return new JAXBElement<String>(_PostVoidComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "AuthorizationCode")
    public JAXBElement<String> createAuthorizationCode(String value) {
        return new JAXBElement<String>(_AuthorizationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TillID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTillID(String value) {
        return new JAXBElement<String>(_TillID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "LocalCurrencyPickup")
    public JAXBElement<TillCountType> createLocalCurrencyPickup(TillCountType value) {
        return new JAXBElement<TillCountType>(_LocalCurrencyPickup_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineItemPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "LineItemProperty")
    public JAXBElement<LineItemPropertyType> createLineItemProperty(LineItemPropertyType value) {
        return new JAXBElement<LineItemPropertyType>(_LineItemProperty_QNAME, LineItemPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ActivityCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createActivityCode(String value) {
        return new JAXBElement<String>(_ActivityCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "StoreBankAudit")
    public JAXBElement<TillCountType> createStoreBankAudit(TillCountType value) {
        return new JAXBElement<TillCountType>(_StoreBankAudit_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "OriginalSerialNumber")
    public JAXBElement<String> createOriginalSerialNumber(String value) {
        return new JAXBElement<String>(_OriginalSerialNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "AssignTillTenderTransfer")
    public JAXBElement<TillCountType> createAssignTillTenderTransfer(TillCountType value) {
        return new JAXBElement<TillCountType>(_AssignTillTenderTransfer_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TareValue")
    public JAXBElement<BigDecimal> createTareValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TareValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ContactFlag")
    public JAXBElement<Boolean> createContactFlag(Boolean value) {
        return new JAXBElement<Boolean>(_ContactFlag_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TareUnitOfMeasureCode")
    public JAXBElement<String> createTareUnitOfMeasureCode(String value) {
        return new JAXBElement<String>(_TareUnitOfMeasureCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Address4")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAddress4(String value) {
        return new JAXBElement<String>(_Address4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Duty")
    public JAXBElement<BigDecimal> createDuty(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Duty_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "VoidReason")
    public JAXBElement<String> createVoidReason(String value) {
        return new JAXBElement<String>(_VoidReason_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PercentOff")
    public JAXBElement<BigDecimal> createPercentOff(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_PercentOff_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ActionCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createActionCode(String value) {
        return new JAXBElement<String>(_ActionCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PostalCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPostalCode(String value) {
        return new JAXBElement<String>(_PostalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "County")
    public JAXBElement<String> createCounty(String value) {
        return new JAXBElement<String>(_County_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "FiscalSessionNumber")
    public JAXBElement<String> createFiscalSessionNumber(String value) {
        return new JAXBElement<String>(_FiscalSessionNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "UnitOfMeasureCode")
    public JAXBElement<String> createUnitOfMeasureCode(String value) {
        return new JAXBElement<String>(_UnitOfMeasureCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Discount")
    public JAXBElement<BigDecimal> createDiscount(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Discount_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "FiscalNumber")
    public JAXBElement<String> createFiscalNumber(String value) {
        return new JAXBElement<String>(_FiscalNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "DeviceId")
    public JAXBElement<String> createDeviceId(String value) {
        return new JAXBElement<String>(_DeviceId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PercentageOfItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PercentageOfItem")
    public JAXBElement<PercentageOfItemType> createPercentageOfItem(PercentageOfItemType value) {
        return new JAXBElement<PercentageOfItemType>(_PercentageOfItem_QNAME, PercentageOfItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "SeriesId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSeriesId(String value) {
        return new JAXBElement<String>(_SeriesId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ResponseText")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createResponseText(String value) {
        return new JAXBElement<String>(_ResponseText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "MidDayTillDeposit")
    public JAXBElement<TillCountType> createMidDayTillDeposit(TillCountType value) {
        return new JAXBElement<TillCountType>(_MidDayTillDeposit_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "FiscalItemDescription")
    public JAXBElement<String> createFiscalItemDescription(String value) {
        return new JAXBElement<String>(_FiscalItemDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Country")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "DiscountReasonCode")
    public JAXBElement<String> createDiscountReasonCode(String value) {
        return new JAXBElement<String>(_DiscountReasonCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ExpirationDateEncrypted")
    public JAXBElement<String> createExpirationDateEncrypted(String value) {
        return new JAXBElement<String>(_ExpirationDateEncrypted_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "CashDrawerID")
    public JAXBElement<String> createCashDrawerID(String value) {
        return new JAXBElement<String>(_CashDrawerID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "LinkTypeCode")
    public JAXBElement<String> createLinkTypeCode(String value) {
        return new JAXBElement<String>(_LinkTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "SerialNumber")
    public JAXBElement<String> createSerialNumber(String value) {
        return new JAXBElement<String>(_SerialNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "DiplomaticTitle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDiplomaticTitle(String value) {
        return new JAXBElement<String>(_DiplomaticTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "RawTaxPercentage")
    public JAXBElement<BigDecimal> createRawTaxPercentage(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RawTaxPercentage_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "OrganizationID")
    public JAXBElement<BigInteger> createOrganizationID(BigInteger value) {
        return new JAXBElement<BigInteger>(_OrganizationID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "City")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Neighborhood")
    public JAXBElement<String> createNeighborhood(String value) {
        return new JAXBElement<String>(_Neighborhood_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ReturnType")
    public JAXBElement<String> createReturnType(String value) {
        return new JAXBElement<String>(_ReturnType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "HashedCardNumber")
    public JAXBElement<String> createHashedCardNumber(String value) {
        return new JAXBElement<String>(_HashedCardNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "MallCertificateID")
    public JAXBElement<BigInteger> createMallCertificateID(BigInteger value) {
        return new JAXBElement<BigInteger>(_MallCertificateID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Territory")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTerritory(String value) {
        return new JAXBElement<String>(_Territory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ErrorText")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createErrorText(String value) {
        return new JAXBElement<String>(_ErrorText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TaxLocationId")
    public JAXBElement<String> createTaxLocationId(String value) {
        return new JAXBElement<String>(_TaxLocationId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "QuantityShipped")
    public JAXBElement<BigDecimal> createQuantityShipped(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_QuantityShipped_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "ReasonComment")
    public JAXBElement<String> createReasonComment(String value) {
        return new JAXBElement<String>(_ReasonComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PayDeductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PayDeduct")
    public JAXBElement<PayDeductType> createPayDeduct(PayDeductType value) {
        return new JAXBElement<PayDeductType>(_PayDeduct_QNAME, PayDeductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TaxGroupId")
    public JAXBElement<String> createTaxGroupId(String value) {
        return new JAXBElement<String>(_TaxGroupId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "AdjudicationCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAdjudicationCode(String value) {
        return new JAXBElement<String>(_AdjudicationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Freight")
    public JAXBElement<BigDecimal> createFreight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Freight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "FiscalTenderID")
    public JAXBElement<String> createFiscalTenderID(String value) {
        return new JAXBElement<String>(_FiscalTenderID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "MeasurementRequired")
    public JAXBElement<Boolean> createMeasurementRequired(Boolean value) {
        return new JAXBElement<Boolean>(_MeasurementRequired_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "OrderType")
    public JAXBElement<String> createOrderType(String value) {
        return new JAXBElement<String>(_OrderType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link POSLogType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nrf-arts.org/IXRetail/namespace/", name = "POSLog")
    public JAXBElement<POSLogType> createPOSLog(POSLogType value) {
        return new JAXBElement<POSLogType>(_POSLog_QNAME, POSLogType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TransCancelReasonCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTransCancelReasonCode(String value) {
        return new JAXBElement<String>(_TransCancelReasonCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "InboundTillID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInboundTillID(String value) {
        return new JAXBElement<String>(_InboundTillID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Tax")
    public JAXBElement<BigDecimal> createTax(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Tax_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "CustomerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCustomerID(String value) {
        return new JAXBElement<String>(_CustomerID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "LocalCurrencyDeposit")
    public JAXBElement<TillCountType> createLocalCurrencyDeposit(TillCountType value) {
        return new JAXBElement<TillCountType>(_LocalCurrencyDeposit_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "DocumentId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDocumentId(String value) {
        return new JAXBElement<String>(_DocumentId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "DiscountId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDiscountId(String value) {
        return new JAXBElement<String>(_DiscountId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "Ps2000")
    public JAXBElement<String> createPs2000(String value) {
        return new JAXBElement<String>(_Ps2000_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "InventoryBucketId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInventoryBucketId(String value) {
        return new JAXBElement<String>(_InventoryBucketId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "BankDeposit")
    public JAXBElement<TillCountType> createBankDeposit(TillCountType value) {
        return new JAXBElement<TillCountType>(_BankDeposit_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "PONumber")
    public JAXBElement<String> createPONumber(String value) {
        return new JAXBElement<String>(_PONumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TillAudit")
    public JAXBElement<TillCountType> createTillAudit(TillCountType value) {
        return new JAXBElement<TillCountType>(_TillAudit_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "FiscalItemID")
    public JAXBElement<String> createFiscalItemID(String value) {
        return new JAXBElement<String>(_FiscalItemID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TillCountType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "BeginTillCount")
    public JAXBElement<TillCountType> createBeginTillCount(TillCountType value) {
        return new JAXBElement<TillCountType>(_BeginTillCount_QNAME, TillCountType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "TareType")
    public JAXBElement<String> createTareType(String value) {
        return new JAXBElement<String>(_TareType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.datavantagecorp.com/xstore/", name = "SystemCycleType")
    public JAXBElement<String> createSystemCycleType(String value) {
        return new JAXBElement<String>(_SystemCycleType_QNAME, String.class, null, value);
    }

}
