//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PayDeductType", namespace = "http://www.datavantagecorp.com/xstore/", propOrder = {
    "payrollDeductEmployee"
})
public class PayDeductType {

    @XmlElement(name = "PayrollDeductEmployee", required = true)
    protected PayrollDeductEmployeeType payrollDeductEmployee;

    /**
     * Gets the value of the payrollDeductEmployee property.
     * 
     * @return
     *     possible object is
     *     {@link PayrollDeductEmployeeType }
     *     
     */
    public PayrollDeductEmployeeType getPayrollDeductEmployee() {
        return payrollDeductEmployee;
    }

    /**
     * Sets the value of the payrollDeductEmployee property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayrollDeductEmployeeType }
     *     
     */
    public void setPayrollDeductEmployee(PayrollDeductEmployeeType value) {
        this.payrollDeductEmployee = value;
    }

}
