//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "POSLogControlTransactionType", propOrder = {
    "operatorID",
    "assignTill",
    "attachTill",
    "removeTill"
})
public class POSLogControlTransactionType {

    @XmlElement(name = "OperatorID")
    protected String operatorID;
    @XmlElement(name = "AssignTill", namespace = "http://www.datavantagecorp.com/xstore/")
    protected AssignTill assignTill;
    @XmlElement(name = "AttachTill", namespace = "http://www.datavantagecorp.com/xstore/")
    protected AttachTill attachTill;
    @XmlElement(name = "RemoveTill", namespace = "http://www.datavantagecorp.com/xstore/")
    protected RemoveTill removeTill;

    /**
     * Gets the value of the operatorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorID() {
        return operatorID;
    }

    /**
     * Sets the value of the operatorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorID(String value) {
        this.operatorID = value;
    }

    /**
     * Gets the value of the assignTill property.
     * 
     * @return
     *     possible object is
     *     {@link AssignTill }
     *     
     */
    public AssignTill getAssignTill() {
        return assignTill;
    }

    /**
     * Sets the value of the assignTill property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignTill }
     *     
     */
    public void setAssignTill(AssignTill value) {
        this.assignTill = value;
    }

    /**
     * Gets the value of the attachTill property.
     * 
     * @return
     *     possible object is
     *     {@link AttachTill }
     *     
     */
    public AttachTill getAttachTill() {
        return attachTill;
    }

    /**
     * Sets the value of the attachTill property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachTill }
     *     
     */
    public void setAttachTill(AttachTill value) {
        this.attachTill = value;
    }

    /**
     * Gets the value of the removeTill property.
     * 
     * @return
     *     possible object is
     *     {@link RemoveTill }
     *     
     */
    public RemoveTill getRemoveTill() {
        return removeTill;
    }

    /**
     * Sets the value of the removeTill property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemoveTill }
     *     
     */
    public void setRemoveTill(RemoveTill value) {
        this.removeTill = value;
    }

}
