//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreviousCustomerOrderType", propOrder = {
    "itemID",
    "description",
    "fiscalItemID",
    "fiscalItemDescription",
    "unitCostPrice",
    "unitListPrice",
    "regularSalesUnitPrice",
    "actualSalesUnitPrice",
    "extendedAmount",
    "quantity",
    "unitOfMeasureCode",
    "measurementRequired",
    "weightEntryMethodCode",
    "tareValue",
    "tareType",
    "tareUnitOfMeasureCode",
    "sellingLocation",
    "merchandiseHierarchy",
    "scannedItemID",
    "authorizationCode",
    "serialNumber",
    "giftReceiptFlag",
    "voidReason",
    "associate",
    "percentageOfItem",
    "retailPriceModifier",
    "tax",
    "transactionLink",
    "lineItemProperty",
    "lineItemAssociation",
    "inventoryReservationID",
    "kit",
    "orderType",
    "accountNumber",
    "pickup"
})
public class PreviousCustomerOrderType {

    @XmlElement(name = "ItemID", required = true)
    protected String itemID;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "FiscalItemID", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String fiscalItemID;
    @XmlElement(name = "FiscalItemDescription", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String fiscalItemDescription;
    @XmlElement(name = "UnitCostPrice")
    protected BigDecimal unitCostPrice;
    @XmlElement(name = "UnitListPrice")
    protected BigDecimal unitListPrice;
    @XmlElement(name = "RegularSalesUnitPrice")
    protected BigDecimal regularSalesUnitPrice;
    @XmlElement(name = "ActualSalesUnitPrice")
    protected BigDecimal actualSalesUnitPrice;
    @XmlElement(name = "ExtendedAmount")
    protected BigDecimal extendedAmount;
    @XmlElement(name = "Quantity")
    protected BigDecimal quantity;
    @XmlElement(name = "UnitOfMeasureCode", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String unitOfMeasureCode;
    @XmlElement(name = "MeasurementRequired", namespace = "http://www.datavantagecorp.com/xstore/")
    protected Boolean measurementRequired;
    @XmlElement(name = "WeightEntryMethodCode", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String weightEntryMethodCode;
    @XmlElement(name = "TareValue", namespace = "http://www.datavantagecorp.com/xstore/")
    protected BigDecimal tareValue;
    @XmlElement(name = "TareType", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String tareType;
    @XmlElement(name = "TareUnitOfMeasureCode", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String tareUnitOfMeasureCode;
    @XmlElement(name = "SellingLocation")
    protected StoreStructure sellingLocation;
    @XmlElement(name = "MerchandiseHierarchy")
    protected List<MerchandiseHierarchyType> merchandiseHierarchy;
    @XmlElement(name = "ScannedItemID", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String scannedItemID;
    @XmlElement(name = "AuthorizationCode", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String authorizationCode;
    @XmlElement(name = "SerialNumber")
    protected String serialNumber;
    @XmlElement(name = "GiftReceiptFlag")
    protected Boolean giftReceiptFlag;
    @XmlElement(name = "VoidReason", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String voidReason;
    @XmlElement(name = "Associate")
    protected List<AssociateType> associate;
    @XmlElement(name = "PercentageOfItem", namespace = "http://www.datavantagecorp.com/xstore/")
    protected List<PercentageOfItemType> percentageOfItem;
    @XmlElement(name = "RetailPriceModifier")
    protected List<RetailPriceModifierType> retailPriceModifier;
    @XmlElement(name = "Tax")
    protected List<TaxType> tax;
    @XmlElement(name = "TransactionLink")
    protected TransactionLinkType transactionLink;
    @XmlElement(name = "LineItemProperty", namespace = "http://www.datavantagecorp.com/xstore/")
    protected List<LineItemPropertyType> lineItemProperty;
    @XmlElement(name = "LineItemAssociation", namespace = "http://www.datavantagecorp.com/xstore/")
    protected List<LineItemAssociation> lineItemAssociation;
    @XmlElement(name = "InventoryReservationID")
    protected String inventoryReservationID;
    @XmlElement(name = "Kit")
    protected List<KitType> kit;
    @XmlElement(name = "OrderType", namespace = "http://www.datavantagecorp.com/xstore/", required = true)
    protected String orderType;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "Pickup")
    protected PickupType pickup;
    @XmlAttribute(name = "Action")
    protected String action;
    @XmlAttribute(name = "ItemType")
    protected String itemType;

    /**
     * Gets the value of the itemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemID() {
        return itemID;
    }

    /**
     * Sets the value of the itemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemID(String value) {
        this.itemID = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the fiscalItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiscalItemID() {
        return fiscalItemID;
    }

    /**
     * Sets the value of the fiscalItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiscalItemID(String value) {
        this.fiscalItemID = value;
    }

    /**
     * Gets the value of the fiscalItemDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiscalItemDescription() {
        return fiscalItemDescription;
    }

    /**
     * Sets the value of the fiscalItemDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiscalItemDescription(String value) {
        this.fiscalItemDescription = value;
    }

    /**
     * Gets the value of the unitCostPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitCostPrice() {
        return unitCostPrice;
    }

    /**
     * Sets the value of the unitCostPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitCostPrice(BigDecimal value) {
        this.unitCostPrice = value;
    }

    /**
     * Gets the value of the unitListPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitListPrice() {
        return unitListPrice;
    }

    /**
     * Sets the value of the unitListPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitListPrice(BigDecimal value) {
        this.unitListPrice = value;
    }

    /**
     * Gets the value of the regularSalesUnitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRegularSalesUnitPrice() {
        return regularSalesUnitPrice;
    }

    /**
     * Sets the value of the regularSalesUnitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRegularSalesUnitPrice(BigDecimal value) {
        this.regularSalesUnitPrice = value;
    }

    /**
     * Gets the value of the actualSalesUnitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActualSalesUnitPrice() {
        return actualSalesUnitPrice;
    }

    /**
     * Sets the value of the actualSalesUnitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActualSalesUnitPrice(BigDecimal value) {
        this.actualSalesUnitPrice = value;
    }

    /**
     * Gets the value of the extendedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getExtendedAmount() {
        return extendedAmount;
    }

    /**
     * Sets the value of the extendedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setExtendedAmount(BigDecimal value) {
        this.extendedAmount = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the unitOfMeasureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasureCode() {
        return unitOfMeasureCode;
    }

    /**
     * Sets the value of the unitOfMeasureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasureCode(String value) {
        this.unitOfMeasureCode = value;
    }

    /**
     * Gets the value of the measurementRequired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMeasurementRequired() {
        return measurementRequired;
    }

    /**
     * Sets the value of the measurementRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMeasurementRequired(Boolean value) {
        this.measurementRequired = value;
    }

    /**
     * Gets the value of the weightEntryMethodCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightEntryMethodCode() {
        return weightEntryMethodCode;
    }

    /**
     * Sets the value of the weightEntryMethodCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightEntryMethodCode(String value) {
        this.weightEntryMethodCode = value;
    }

    /**
     * Gets the value of the tareValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTareValue() {
        return tareValue;
    }

    /**
     * Sets the value of the tareValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTareValue(BigDecimal value) {
        this.tareValue = value;
    }

    /**
     * Gets the value of the tareType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTareType() {
        return tareType;
    }

    /**
     * Sets the value of the tareType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTareType(String value) {
        this.tareType = value;
    }

    /**
     * Gets the value of the tareUnitOfMeasureCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTareUnitOfMeasureCode() {
        return tareUnitOfMeasureCode;
    }

    /**
     * Sets the value of the tareUnitOfMeasureCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTareUnitOfMeasureCode(String value) {
        this.tareUnitOfMeasureCode = value;
    }

    /**
     * Gets the value of the sellingLocation property.
     * 
     * @return
     *     possible object is
     *     {@link StoreStructure }
     *     
     */
    public StoreStructure getSellingLocation() {
        return sellingLocation;
    }

    /**
     * Sets the value of the sellingLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link StoreStructure }
     *     
     */
    public void setSellingLocation(StoreStructure value) {
        this.sellingLocation = value;
    }

    /**
     * Gets the value of the merchandiseHierarchy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the merchandiseHierarchy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMerchandiseHierarchy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MerchandiseHierarchyType }
     * 
     * 
     */
    public List<MerchandiseHierarchyType> getMerchandiseHierarchy() {
        if (merchandiseHierarchy == null) {
            merchandiseHierarchy = new ArrayList<MerchandiseHierarchyType>();
        }
        return this.merchandiseHierarchy;
    }

    /**
     * Gets the value of the scannedItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScannedItemID() {
        return scannedItemID;
    }

    /**
     * Sets the value of the scannedItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScannedItemID(String value) {
        this.scannedItemID = value;
    }

    /**
     * Gets the value of the authorizationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationCode() {
        return authorizationCode;
    }

    /**
     * Sets the value of the authorizationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationCode(String value) {
        this.authorizationCode = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the giftReceiptFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGiftReceiptFlag() {
        return giftReceiptFlag;
    }

    /**
     * Sets the value of the giftReceiptFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGiftReceiptFlag(Boolean value) {
        this.giftReceiptFlag = value;
    }

    /**
     * Gets the value of the voidReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoidReason() {
        return voidReason;
    }

    /**
     * Sets the value of the voidReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoidReason(String value) {
        this.voidReason = value;
    }

    /**
     * Gets the value of the associate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssociateType }
     * 
     * 
     */
    public List<AssociateType> getAssociate() {
        if (associate == null) {
            associate = new ArrayList<AssociateType>();
        }
        return this.associate;
    }

    /**
     * Gets the value of the percentageOfItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the percentageOfItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPercentageOfItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PercentageOfItemType }
     * 
     * 
     */
    public List<PercentageOfItemType> getPercentageOfItem() {
        if (percentageOfItem == null) {
            percentageOfItem = new ArrayList<PercentageOfItemType>();
        }
        return this.percentageOfItem;
    }

    /**
     * Gets the value of the retailPriceModifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the retailPriceModifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRetailPriceModifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RetailPriceModifierType }
     * 
     * 
     */
    public List<RetailPriceModifierType> getRetailPriceModifier() {
        if (retailPriceModifier == null) {
            retailPriceModifier = new ArrayList<RetailPriceModifierType>();
        }
        return this.retailPriceModifier;
    }

    /**
     * Gets the value of the tax property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tax property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTax().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TaxType }
     * 
     * 
     */
    public List<TaxType> getTax() {
        if (tax == null) {
            tax = new ArrayList<TaxType>();
        }
        return this.tax;
    }

    /**
     * Gets the value of the transactionLink property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionLinkType }
     *     
     */
    public TransactionLinkType getTransactionLink() {
        return transactionLink;
    }

    /**
     * Sets the value of the transactionLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionLinkType }
     *     
     */
    public void setTransactionLink(TransactionLinkType value) {
        this.transactionLink = value;
    }

    /**
     * Gets the value of the lineItemProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItemProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItemProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineItemPropertyType }
     * 
     * 
     */
    public List<LineItemPropertyType> getLineItemProperty() {
        if (lineItemProperty == null) {
            lineItemProperty = new ArrayList<LineItemPropertyType>();
        }
        return this.lineItemProperty;
    }

    /**
     * Gets the value of the lineItemAssociation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItemAssociation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItemAssociation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineItemAssociation }
     * 
     * 
     */
    public List<LineItemAssociation> getLineItemAssociation() {
        if (lineItemAssociation == null) {
            lineItemAssociation = new ArrayList<LineItemAssociation>();
        }
        return this.lineItemAssociation;
    }

    /**
     * Gets the value of the inventoryReservationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryReservationID() {
        return inventoryReservationID;
    }

    /**
     * Sets the value of the inventoryReservationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryReservationID(String value) {
        this.inventoryReservationID = value;
    }

    /**
     * Gets the value of the kit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KitType }
     * 
     * 
     */
    public List<KitType> getKit() {
        if (kit == null) {
            kit = new ArrayList<KitType>();
        }
        return this.kit;
    }

    /**
     * Gets the value of the orderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * Sets the value of the orderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderType(String value) {
        this.orderType = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the pickup property.
     * 
     * @return
     *     possible object is
     *     {@link PickupType }
     *     
     */
    public PickupType getPickup() {
        return pickup;
    }

    /**
     * Sets the value of the pickup property.
     * 
     * @param value
     *     allowed object is
     *     {@link PickupType }
     *     
     */
    public void setPickup(PickupType value) {
        this.pickup = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the itemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * Sets the value of the itemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemType(String value) {
        this.itemType = value;
    }

}
