//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetailTransactionType", propOrder = {
    "lineItem",
    "total",
    "roundedTotal",
    "customer",
    "customerAccount",
    "employeeSaleId",
    "transactionLink",
    "postVoidReasonCode",
    "transCancelReasonCode",
    "postVoidComment",
    "flightInformation"
})
public class RetailTransactionType {

    @XmlElement(name = "LineItem")
    protected List<LineItemType> lineItem;
    @XmlElement(name = "Total")
    protected List<TotalType> total;
    @XmlElement(name = "RoundedTotal")
    protected BigDecimal roundedTotal;
    @XmlElement(name = "Customer")
    protected PoslogCustomerType customer;
    @XmlElement(name = "CustomerAccount")
    protected CustomerAccountType customerAccount;
    @XmlElement(name = "EmployeeSaleId", namespace = "http://www.datavantagecorp.com/xstore/")
    protected BigInteger employeeSaleId;
    @XmlElement(name = "TransactionLink")
    protected TransactionLinkType transactionLink;
    @XmlElement(name = "PostVoidReasonCode", namespace = "http://www.datavantagecorp.com/xstore/")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String postVoidReasonCode;
    @XmlElement(name = "TransCancelReasonCode", namespace = "http://www.datavantagecorp.com/xstore/")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String transCancelReasonCode;
    @XmlElement(name = "PostVoidComment", namespace = "http://www.datavantagecorp.com/xstore/")
    protected String postVoidComment;
    @XmlElement(name = "FlightInformation", namespace = "http://www.datavantagecorp.com/xstore/")
    protected FlightInformation flightInformation;
    @XmlAttribute(name = "Version")
    protected String version;
    @XmlAttribute(name = "TypeCode")
    protected String typeCode;
    @XmlAttribute(name = "TransactionStatus")
    protected String transactionStatus;

    /**
     * Gets the value of the lineItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LineItemType }
     * 
     * 
     */
    public List<LineItemType> getLineItem() {
        if (lineItem == null) {
            lineItem = new ArrayList<LineItemType>();
        }
        return this.lineItem;
    }

    /**
     * Gets the value of the total property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the total property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TotalType }
     * 
     * 
     */
    public List<TotalType> getTotal() {
        if (total == null) {
            total = new ArrayList<TotalType>();
        }
        return this.total;
    }

    /**
     * Gets the value of the roundedTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRoundedTotal() {
        return roundedTotal;
    }

    /**
     * Sets the value of the roundedTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRoundedTotal(BigDecimal value) {
        this.roundedTotal = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link PoslogCustomerType }
     *     
     */
    public PoslogCustomerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoslogCustomerType }
     *     
     */
    public void setCustomer(PoslogCustomerType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the customerAccount property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerAccountType }
     *     
     */
    public CustomerAccountType getCustomerAccount() {
        return customerAccount;
    }

    /**
     * Sets the value of the customerAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerAccountType }
     *     
     */
    public void setCustomerAccount(CustomerAccountType value) {
        this.customerAccount = value;
    }

    /**
     * Gets the value of the employeeSaleId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEmployeeSaleId() {
        return employeeSaleId;
    }

    /**
     * Sets the value of the employeeSaleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEmployeeSaleId(BigInteger value) {
        this.employeeSaleId = value;
    }

    /**
     * Gets the value of the transactionLink property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionLinkType }
     *     
     */
    public TransactionLinkType getTransactionLink() {
        return transactionLink;
    }

    /**
     * Sets the value of the transactionLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionLinkType }
     *     
     */
    public void setTransactionLink(TransactionLinkType value) {
        this.transactionLink = value;
    }

    /**
     * Gets the value of the postVoidReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostVoidReasonCode() {
        return postVoidReasonCode;
    }

    /**
     * Sets the value of the postVoidReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostVoidReasonCode(String value) {
        this.postVoidReasonCode = value;
    }

    /**
     * Gets the value of the transCancelReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransCancelReasonCode() {
        return transCancelReasonCode;
    }

    /**
     * Sets the value of the transCancelReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransCancelReasonCode(String value) {
        this.transCancelReasonCode = value;
    }

    /**
     * Gets the value of the postVoidComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostVoidComment() {
        return postVoidComment;
    }

    /**
     * Sets the value of the postVoidComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostVoidComment(String value) {
        this.postVoidComment = value;
    }

    /**
     * Gets the value of the flightInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FlightInformation }
     *     
     */
    public FlightInformation getFlightInformation() {
        return flightInformation;
    }

    /**
     * Sets the value of the flightInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightInformation }
     *     
     */
    public void setFlightInformation(FlightInformation value) {
        this.flightInformation = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the typeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the value of the typeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeCode(String value) {
        this.typeCode = value;
    }

    /**
     * Gets the value of the transactionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionStatus() {
        return transactionStatus;
    }

    /**
     * Sets the value of the transactionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionStatus(String value) {
        this.transactionStatus = value;
    }

}
