//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaxOverrideType", propOrder = {
    "originalTaxPercent",
    "originalTaxAmount",
    "newTaxPercent",
    "newTaxAmount",
    "reasonCode"
})
public class TaxOverrideType {

    @XmlElement(name = "OriginalTaxPercent", required = true)
    protected BigDecimal originalTaxPercent;
    @XmlElement(name = "OriginalTaxAmount", required = true)
    protected BigDecimal originalTaxAmount;
    @XmlElement(name = "NewTaxPercent", required = true)
    protected BigDecimal newTaxPercent;
    @XmlElement(name = "NewTaxAmount", required = true)
    protected BigDecimal newTaxAmount;
    @XmlElement(name = "ReasonCode", required = true)
    protected String reasonCode;

    /**
     * Gets the value of the originalTaxPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOriginalTaxPercent() {
        return originalTaxPercent;
    }

    /**
     * Sets the value of the originalTaxPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOriginalTaxPercent(BigDecimal value) {
        this.originalTaxPercent = value;
    }

    /**
     * Gets the value of the originalTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOriginalTaxAmount() {
        return originalTaxAmount;
    }

    /**
     * Sets the value of the originalTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOriginalTaxAmount(BigDecimal value) {
        this.originalTaxAmount = value;
    }

    /**
     * Gets the value of the newTaxPercent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNewTaxPercent() {
        return newTaxPercent;
    }

    /**
     * Sets the value of the newTaxPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNewTaxPercent(BigDecimal value) {
        this.newTaxPercent = value;
    }

    /**
     * Gets the value of the newTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNewTaxAmount() {
        return newTaxAmount;
    }

    /**
     * Sets the value of the newTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNewTaxAmount(BigDecimal value) {
        this.newTaxAmount = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

}
