//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TenderTypeCountType", namespace = "http://www.datavantagecorp.com/xstore/", propOrder = {
    "tenderTypeTotal",
    "tenderCount",
    "tenderTypeSerializedCount"
})
public class TenderTypeCountType {

    @XmlElement(name = "TenderTypeTotal", required = true)
    protected TenderTotalType tenderTypeTotal;
    @XmlElement(name = "TenderCount")
    protected List<TenderCountType> tenderCount;
    @XmlElement(name = "TenderTypeSerializedCount")
    protected List<TenderTypeSerializedCountType> tenderTypeSerializedCount;
    @XmlAttribute(name = "TenderType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tenderType;

    /**
     * Gets the value of the tenderTypeTotal property.
     * 
     * @return
     *     possible object is
     *     {@link TenderTotalType }
     *     
     */
    public TenderTotalType getTenderTypeTotal() {
        return tenderTypeTotal;
    }

    /**
     * Sets the value of the tenderTypeTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenderTotalType }
     *     
     */
    public void setTenderTypeTotal(TenderTotalType value) {
        this.tenderTypeTotal = value;
    }

    /**
     * Gets the value of the tenderCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tenderCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTenderCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TenderCountType }
     * 
     * 
     */
    public List<TenderCountType> getTenderCount() {
        if (tenderCount == null) {
            tenderCount = new ArrayList<TenderCountType>();
        }
        return this.tenderCount;
    }

    /**
     * Gets the value of the tenderTypeSerializedCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tenderTypeSerializedCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTenderTypeSerializedCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TenderTypeSerializedCountType }
     * 
     * 
     */
    public List<TenderTypeSerializedCountType> getTenderTypeSerializedCount() {
        if (tenderTypeSerializedCount == null) {
            tenderTypeSerializedCount = new ArrayList<TenderTypeSerializedCountType>();
        }
        return this.tenderTypeSerializedCount;
    }

    /**
     * Gets the value of the tenderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderType() {
        return tenderType;
    }

    /**
     * Sets the value of the tenderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderType(String value) {
        this.tenderType = value;
    }

}
