//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TenderTypeSerializedCountType", namespace = "http://www.datavantagecorp.com/xstore/", propOrder = {
    "tenderCount"
})
public class TenderTypeSerializedCountType {

    @XmlElement(name = "TenderCount", required = true)
    protected TenderCountType tenderCount;
    @XmlAttribute(name = "TenderType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String tenderType;

    /**
     * Gets the value of the tenderCount property.
     * 
     * @return
     *     possible object is
     *     {@link TenderCountType }
     *     
     */
    public TenderCountType getTenderCount() {
        return tenderCount;
    }

    /**
     * Sets the value of the tenderCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TenderCountType }
     *     
     */
    public void setTenderCount(TenderCountType value) {
        this.tenderCount = value;
    }

    /**
     * Gets the value of the tenderType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTenderType() {
        return tenderType;
    }

    /**
     * Sets the value of the tenderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTenderType(String value) {
        this.tenderType = value;
    }

}
