//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 10:00:19 AM EST 
//


package com.backcountry.store.orchestrator.models;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TillCountType", namespace = "http://www.datavantagecorp.com/xstore/", propOrder = {
    "inboundTillID",
    "inboundTillEmployeePartyID",
    "outboundTillID",
    "outboundTillEmployeePartyID",
    "cashRemainedInTill",
    "safeBagTransactionLink",
    "tenderTypeCount"
})
public class TillCountType {

    @XmlElement(name = "InboundTillID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String inboundTillID;
    @XmlElement(name = "InboundTillEmployeePartyID")
    protected BigInteger inboundTillEmployeePartyID;
    @XmlElement(name = "OutboundTillID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String outboundTillID;
    @XmlElement(name = "OutboundTillEmployeePartyID")
    protected BigInteger outboundTillEmployeePartyID;
    @XmlElement(name = "CashRemainedInTill")
    protected List<CashRemainedInTillType> cashRemainedInTill;
    @XmlElement(name = "SafeBagTransactionLink")
    protected List<SafeBagTransactionType> safeBagTransactionLink;
    @XmlElement(name = "TenderTypeCount")
    protected List<TenderTypeCountType> tenderTypeCount;

    /**
     * Gets the value of the inboundTillID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInboundTillID() {
        return inboundTillID;
    }

    /**
     * Sets the value of the inboundTillID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInboundTillID(String value) {
        this.inboundTillID = value;
    }

    /**
     * Gets the value of the inboundTillEmployeePartyID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInboundTillEmployeePartyID() {
        return inboundTillEmployeePartyID;
    }

    /**
     * Sets the value of the inboundTillEmployeePartyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInboundTillEmployeePartyID(BigInteger value) {
        this.inboundTillEmployeePartyID = value;
    }

    /**
     * Gets the value of the outboundTillID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutboundTillID() {
        return outboundTillID;
    }

    /**
     * Sets the value of the outboundTillID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutboundTillID(String value) {
        this.outboundTillID = value;
    }

    /**
     * Gets the value of the outboundTillEmployeePartyID property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOutboundTillEmployeePartyID() {
        return outboundTillEmployeePartyID;
    }

    /**
     * Sets the value of the outboundTillEmployeePartyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutboundTillEmployeePartyID(BigInteger value) {
        this.outboundTillEmployeePartyID = value;
    }

    /**
     * Gets the value of the cashRemainedInTill property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cashRemainedInTill property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCashRemainedInTill().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CashRemainedInTillType }
     * 
     * 
     */
    public List<CashRemainedInTillType> getCashRemainedInTill() {
        if (cashRemainedInTill == null) {
            cashRemainedInTill = new ArrayList<CashRemainedInTillType>();
        }
        return this.cashRemainedInTill;
    }

    /**
     * Gets the value of the safeBagTransactionLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the safeBagTransactionLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSafeBagTransactionLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SafeBagTransactionType }
     * 
     * 
     */
    public List<SafeBagTransactionType> getSafeBagTransactionLink() {
        if (safeBagTransactionLink == null) {
            safeBagTransactionLink = new ArrayList<SafeBagTransactionType>();
        }
        return this.safeBagTransactionLink;
    }

    /**
     * Gets the value of the tenderTypeCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tenderTypeCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTenderTypeCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TenderTypeCountType }
     * 
     * 
     */
    public List<TenderTypeCountType> getTenderTypeCount() {
        if (tenderTypeCount == null) {
            tenderTypeCount = new ArrayList<TenderTypeCountType>();
        }
        return this.tenderTypeCount;
    }

}
